apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-chamados
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-chamados
  template:
    metadata:
      labels:
        app: api-chamados
    spec:
      containers:
      - name: api-chamados
        image: rjorge/api-chamados
        ports:
        - name: nodejs-port
          containerPort: 8080
      nodeSelector:
        hardware: high-spec
