apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-chamados
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-chamados
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
