apiVersion: v1
kind: ReplicationController
metadata:
  name: api-chamados
spec:
  replicas: 2
  selector:
    app: api-chamados
  template:
    metadata:
      labels:
        app: api-chamados
    spec:
      containers:
      - name: api-chamados
        image: rjorge/api-chamados
        ports:
        - name: nodejs-port
          containerPort: 8080
